serenity.project.name=Way2Automation Serenity Project
webdriver.base.url=http://gmail.com

webdriver.driver=chrome
//webdriver.driver=firefox
webdriver.chrome.driver=src/test/resources/drivers/chromedriver.exe
//webdriver.firefox.driver=src/test/resources/drivers/geckodriver.exe